version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
install:
  - choco install gitversion.portable -pre -y

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

assembly_info:
  patch: false

before_build:
  - cmd: nuget restore
  - ps: gitversion /l console /output buildserver /updateAssemblyInfo

build:
  project: restfluencing.sln
  publish_nuget: true
  verbosity: minimal

after_build:
  - cmd: ECHO nuget pack .\src\RestFluencing.Core\restfluencing.Core.csproj -version "%GitVersion_NuGetVersion%" -prop "target=%CONFIGURATION%"
  - cmd: nuget pack .\src\RestFluencing.Core\restfluencing.Core.csproj -version "%GitVersion_NuGetVersion%" -prop "target=%CONFIGURATION%"
  - cmd: appveyor PushArtifact "RestFluencing.Core.%GitVersion_NuGetVersion%.nupkg"
test:
  assemblies:
    only:
    - RestFluencing.Tests.dll

